/**
 * English — Literature & Language Arts
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const english: WordCluePair[] = [
  { word: 'ox', clue: 'A domesticated bovine animal' },
  { word: 'run', clue: 'To move swiftly on foot' },
  { word: 'act', clue: 'A main division of a play' },
  { word: 'pen', clue: 'A tool used for writing' },
  { word: 'pun', clue: 'A play on words' },
  { word: 'sim', clue: 'A simulation or similarity' },
  { word: 'met', clue: 'Past tense of \'meet\'' },
  { word: 'noun', clue: 'A person, place, thing, or idea' },
  { word: 'verb', clue: 'A word that describes an action or state' },
  { word: 'tone', clue: 'The author\'s attitude toward the subject' },
  { word: 'plot', clue: 'The sequence of events in a story' },
  { word: 'mood', clue: 'The emotional feeling of a piece' },
  { word: 'edit', clue: 'To revise or correct a text' },
  { word: 'poem', clue: 'A composition in verse' },
  { word: 'rhyme', clue: 'A repetition of similar sounds' },
  { word: 'theme', clue: 'The main idea or message of a work' },
  { word: 'irony', clue: 'A contrast between expectation and reality' },
  { word: 'genre', clue: 'A category of literature or art' },
  { word: 'prose', clue: 'Ordinary written language' },
  { word: 'draft', clue: 'A preliminary version of a text' },
  { word: 'title', clue: 'The name of a work' },
  { word: 'clause', clue: 'A group of words with subject and verb' },
  { word: 'quote', clue: 'A repetition of someone else\'s words' },
  { word: 'intro', clue: 'The beginning section of a piece' },
  { word: 'simile', clue: 'A comparison using \'like\' or \'as\'' },
  { word: 'symbol', clue: 'An object representing an idea' },
  { word: 'author', clue: 'The writer of a literary work' },
  { word: 'phrase', clue: 'A small group of words' },
  { word: 'editor', clue: 'Someone who prepares text for publication' },
  { word: 'speech', clue: 'A spoken presentation' },
  { word: 'dialog', clue: 'A conversation in a story' },
  { word: 'couplet', clue: 'Two lines of verse, often rhyming' },
  { word: 'revise', clue: 'To improve a piece of writing' },
  { word: 'thesis', clue: 'Main point in an essay' },
  { word: 'subject', clue: 'What the sentence is about' },
  { word: 'summary', clue: 'A short version of a longer text' },
  { word: 'fiction', clue: 'Imagined narrative writing' },
  { word: 'imagery', clue: 'Descriptive language for the senses' },
  { word: 'setting', clue: 'Time and place of a story' },
  { word: 'context', clue: 'Circumstances surrounding a text' },
  { word: 'villain', clue: 'The antagonist in a story' },
  { word: 'grammar', clue: 'Rules of a language' },
  { word: 'message', clue: 'The idea a writer communicates' },
  { word: 'trigger', clue: 'A stimulus that sparks a response' },
  { word: 'sentence', clue: 'A complete thought with subject and verb' },
  { word: 'conflict', clue: 'A struggle or problem in a story' },
  { word: 'dialogue', clue: 'Spoken interaction in writing' },
  { word: 'evidence', clue: 'Proof from the text' },
  { word: 'audience', clue: 'Who the work is intended for' },
  { word: 'analysis', clue: 'Detailed examination of a work' },
  { word: 'allusion', clue: 'A reference to another work' },
  { word: 'blueprint', clue: 'Detailed plan or structure' },
  { word: 'parody', clue: 'Imitation for comic effect' },
  { word: 'narrator', clue: 'The voice telling the story' },
  { word: 'predicate', clue: 'Part of sentence telling what subject does' },
  { word: 'flashback', clue: 'Scene showing past events' },
  { word: 'underline', clue: 'To emphasize text' },
  { word: 'figurative', clue: 'Not literal; symbolic meaning' },
  { word: 'resolution', clue: 'End or solution of a conflict' },
  { word: 'antonym', clue: 'Word opposite in meaning' },
  { word: 'syllable', clue: 'A single unit of sound in a word' },
  { word: 'criticism', clue: 'Judgment or analysis of work' },
  { word: 'character', clue: 'Person in a story' },
  { word: 'structure', clue: 'The way a text is organized' },
  { word: 'adjective', clue: 'Word describing a noun' },
  { word: 'hyperbole', clue: 'Exaggeration for effect' },
  { word: 'foreshadow', clue: 'Hinting at future events' },
  { word: 'conclusion', clue: 'The ending or final summary' },
  { word: 'persuasive', clue: 'Trying to convince the reader' },
  { word: 'comparison', clue: 'Identifying similarities' },
  { word: 'expression', clue: 'A way of showing ideas or feelings' },
  { word: 'narrative', clue: 'Story or account of events' },
  { word: 'antagonist', clue: 'Character who opposes the protagonist' },
  { word: 'connotative', clue: 'Implied meaning beyond the literal' },
];
