/**
 * Unit 3 — Boolean Expressions and if Statements
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_3: WordCluePair[] = [
  { word: 'if', clue: 'Keyword to start a conditional statement' },
  { word: 'or', clue: 'Logical operator ||, true if at least one operand is true' },
  { word: 'eq', clue: 'Abbreviation for \'equals\', often used with == symbol' },
  { word: 'ne', clue: 'Abbreviation for \'not equal\', often used with != symbol' },
  { word: 'gt', clue: 'Abbreviation for \'greater than\', symbol >' },
  { word: 'lt', clue: 'Abbreviation for \'less than\', symbol <' },
  { word: 'and', clue: 'Logical operator &&, true if both operands are true' },
  { word: 'not', clue: 'Logical operator !, inverts a boolean value' },
  { word: 'xor', clue: 'Logical operator for exclusive OR (true if operands differ)' },
  { word: 'end', clue: 'Marks the logical termination of a code block' },
  { word: 'run', clue: 'To cause the program to execute statements' },
  { word: 'key', clue: 'A reserved word in Java, like \'if\' or \'else\'' },
  { word: 'bit', clue: 'A single binary digit, basis of boolean values' },
  { word: 'else', clue: 'Keyword for code executed if \'if\' condition is false' },
  { word: 'true', clue: 'A boolean literal representing a true condition' },
  { word: 'less', clue: 'Relational operator <, for less than comparison' },
  { word: 'then', clue: 'Implied keyword following an \'if\' condition before its block' },
  { word: 'code', clue: 'Statements executed within a conditional block' },
  { word: 'flow', clue: 'Short for control flow, the order of execution' },
  { word: 'path', clue: 'A specific sequence of executed statements' },
  { word: 'skip', clue: 'What happens to a block if its condition is false' },
  { word: 'test', clue: 'A condition in an \'if\' statement acts as this' },
  { word: 'flag', clue: 'A boolean variable used to signal a state or condition' },
  { word: 'data', clue: 'Information, like a boolean value, processed by conditions' },
  { word: 'false', clue: 'A boolean literal representing an untrue condition' },
  { word: 'equal', clue: 'Relational operator ==, tests for equality' },
  { word: 'logic', clue: 'The system of reasoning used in boolean expressions' },
  { word: 'block', clue: 'A group of statements enclosed in braces {}' },
  { word: 'scope', clue: 'The region where a variable is accessible' },
  { word: 'brace', clue: 'Symbol { or } used to define a code block' },
  { word: 'truth', clue: 'The quality of being true, as in a truth table' },
  { word: 'check', clue: 'To evaluate a condition or verify a state' },
  { word: 'chain', clue: 'A sequence of if-else if-else statements' },
  { word: 'guard', clue: 'An if statement preventing errors or unwanted execution' },
  { word: 'value', clue: 'A boolean literal (true or false) is a ___' },
  { word: 'valid', clue: 'A condition might check if input is ___' },
  { word: 'elseif', clue: 'Keyword for an \'else if\' conditional check' },
  { word: 'nested', clue: 'An if statement inside another if statement' },
  { word: 'binary', clue: 'Having two states, like boolean true/false' },
  { word: 'branch', clue: 'A point in control flow where execution can diverge' },
  { word: 'clause', clue: 'An \'if\' or \'else\' part of a conditional statement' },
  { word: 'result', clue: 'The boolean outcome of evaluating an expression' },
  { word: 'negate', clue: 'To reverse a boolean value using the NOT operator' },
  { word: 'either', clue: 'Used in logic like \'either A or B\' (inclusive OR)' },
  { word: 'syntax', clue: 'The grammatical rules for writing Java code' },
  { word: 'op', clue: 'Common abbreviation for \'operator\'' },
  { word: 'assert', clue: 'A statement to check a condition, for debugging' },
  { word: 'boolean', clue: 'A primitive data type for true/false values' },
  { word: 'greater', clue: 'Relational operator >, for greater than comparison' },
  { word: 'compare', clue: 'To evaluate the relationship between two values' },
  { word: 'logical', clue: 'Type of operator like &&, ||, !' },
  { word: 'default', clue: 'The code path taken if no prior conditions are met' },
  { word: 'outcome', clue: 'The result (true or false) of a conditional test' },
  { word: 'execute', clue: 'To carry out the instructions in a code block' },
  { word: 'boolexp', clue: 'Short for Boolean Expression' },
  { word: 'cascade', clue: 'An if-else if-else chain can form this structure' },
  { word: 'resolve', clue: 'To determine the final boolean value of an expression' },
  { word: 'logicop', clue: 'Short for Logical Operator' },
  { word: 'control', clue: 'Control flow statements direct program execution' },
  { word: 'notequal', clue: 'Relational operator !=, tests for inequality' },
  { word: 'lessoreq', clue: 'Relational operator <= (less than or equal to)' },
  { word: 'relation', clue: 'A comparison between values, e.g., less than, equal to' },
  { word: 'compound', clue: 'A condition formed by joining multiple conditions' },
  { word: 'evaluate', clue: 'To determine the boolean result of an expression' },
  { word: 'operator', clue: 'A symbol (e.g., &&, ==, <) that performs an operation' },
  { word: 'grouping', clue: 'Using parentheses () to control evaluation order' },
  { word: 'dangling', clue: 'Refers to the \'dangling else\' ambiguity problem' },
  { word: 'demorgan', clue: 'De Morgan\'s laws for simplifying boolean expressions' },
  { word: 'flowpath', clue: 'The specific route of execution through conditional logic' },
  { word: 'boologic', clue: 'Abbreviation for Boolean Logic' },
  { word: 'opposite', clue: 'The \'not\' operator gives the ___ boolean value' },
  { word: 'condition', clue: 'An expression that evaluates to true or false' },
  { word: 'greatereq', clue: 'Relational operator >= (greater than or equal to)' },
  { word: 'branching', clue: 'The act of choosing between different paths of execution' },
  { word: 'exclusive', clue: 'Mutually ___ conditions: only one can be true (XOR idea)' },
  { word: 'statement', clue: 'A complete unit of execution, like an \'if\' statement' },
  { word: 'selection', clue: 'A control structure that chooses which code to run' },
  { word: 'structure', clue: 'Control ___ like if-else directs program flow' },
  { word: 'predicate', clue: 'A method or expression that returns a boolean value' },
  { word: 'alternate', clue: 'An alternative path in an if-else structure' },
  { word: 'indenting', clue: 'Formatting code to show nesting levels visually' },
  { word: 'shortfall', clue: 'When short-circuiting stops evaluation early' },
  { word: 'certainty', clue: 'The goal of evaluating a boolean condition' },
  { word: 'comparison', clue: 'The act of comparing two values, yields a boolean' },
  { word: 'relational', clue: 'Type of operator that compares values (e.g., >, <, ==)' },
  { word: 'truthtable', clue: 'A table showing all outcomes of a boolean expression' },
  { word: 'precedence', clue: 'Operator ___ rules determine evaluation order' },
  { word: 'expression', clue: 'Code that evaluates to a value, often boolean in ifs' },
  { word: 'circuiting', clue: 'Short-___ evaluation (&&, ||) stops when outcome is known' },
  { word: 'nestedelse', clue: 'An \'else\' that belongs to an inner \'if\' statement' },
  { word: 'equivalent', clue: 'Two boolean expressions are ___ if they have identical truth tables' },
  { word: 'sequential', clue: 'Default execution order, one statement after another' },
  { word: 'consequent', clue: 'The block of code executed if an \'if\' condition is true' },
  { word: 'exhaustive', clue: 'Checking all possible conditions or paths' },
];
