/**
 * Unit 2 — Using Objects
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_2: WordCluePair[] = [
  { word: 'is', clue: 'A common prefix for boolean accessor methods (e.g., isEmpty)' },
  { word: 'pi', clue: 'Mathematical constant available in the Math class (Math.PI)' },
  { word: 'id', clue: 'An identifier, often used for instance variables' },
  { word: 'no', clue: 'Can refer to \'no-argument\' as in a no-arg constructor' },
  { word: 'new', clue: 'Keyword used to instantiate an object from a class' },
  { word: 'dot', clue: 'Operator (.) used to access members (fields or methods) of an object' },
  { word: 'get', clue: 'Common prefix for accessor (getter) methods' },
  { word: 'set', clue: 'Common prefix for mutator (setter) methods' },
  { word: 'api', clue: 'Application Programming Interface, defines how objects interact' },
  { word: 'abs', clue: 'Method in Math class for absolute value (Math.abs)' },
  { word: 'pow', clue: 'Method in Math class for exponentiation (Math.pow)' },
  { word: 'arg', clue: 'Short for argument, a value passed to a method' },
  { word: 'try', clue: 'Keyword used in exception handling, often with Scanner' },
  { word: 'max', clue: 'Method in Math class to find the larger of two values (Math.max)' },
  { word: 'min', clue: 'Method in Math class to find the smaller of two values (Math.min)' },
  { word: 'null', clue: 'A literal representing an uninitialized object reference' },
  { word: 'math', clue: 'A utility class in Java providing static methods for numeric operations' },
  { word: 'void', clue: 'Keyword indicating a method does not return any value' },
  { word: 'this', clue: 'Keyword referring to the current object instance' },
  { word: 'true', clue: 'A boolean literal value' },
  { word: 'else', clue: 'Used with \'if\' for conditional logic' },
  { word: 'char', clue: 'Primitive data type, also used in String methods like charAt' },
  { word: 'data', clue: 'Information stored in an object\'s fields' },
  { word: 'type', clue: 'The classification of an object or variable (e.g., String, int)' },
  { word: 'call', clue: 'The act of invoking a method' },
  { word: 'sqrt', clue: 'Method in Math class for square root (Math.sqrt)' },
  { word: 'copy', clue: 'Creating a new object with the same state as another' },
  { word: 'heap', clue: 'The memory area where objects are allocated' },
  { word: 'name', clue: 'Often used for identifiers or String representations' },
  { word: 'byte', clue: 'Primitive data type, wrapper class is Byte' },
  { word: 'class', clue: 'The blueprint or template for creating objects' },
  { word: 'state', clue: 'The collective values of an object\'s instance variables' },
  { word: 'field', clue: 'An instance variable, a piece of data within an object' },
  { word: 'super', clue: 'Keyword to refer to the parent class, often used in constructors or overriding' },
  { word: 'index', clue: 'A numerical position, used in String or array access' },
  { word: 'parse', clue: 'To convert a String to a numeric type (e.g., Integer.parseInt)' },
  { word: 'round', clue: 'Method in Math class to round a float or double (Math.round)' },
  { word: 'local', clue: 'A variable declared inside a method' },
  { word: 'final', clue: 'Keyword to make a variable a constant or prevent method overriding/class inheritance' },
  { word: 'throw', clue: 'Keyword to signal an exception explicitly' },
  { word: 'short', clue: 'Primitive data type, wrapper class is Short' },
  { word: 'nargs', clue: 'Abbreviation for \'number of arguments\'' },
  { word: 'object', clue: 'An instance of a class, representing a specific entity' },
  { word: 'method', clue: 'A named block of code associated with a class or object that performs a task' },
  { word: 'random', clue: 'Class (java.util.Random) used to generate pseudo-random numbers' },
  { word: 'string', clue: 'An object representing a sequence of characters' },
  { word: 'length', clue: 'Method of String class to get its number of characters; also array property' },
  { word: 'equals', clue: 'Method used to compare the content of two objects (especially Strings)' },
  { word: 'charat', clue: 'String method (charAt) to get a character at a specific index' },
  { word: 'return', clue: 'Keyword used to send a value back from a method to its caller' },
  { word: 'import', clue: 'Statement to make classes from other packages available' },
  { word: 'static', clue: 'Keyword indicating a member belongs to the class itself, not to instances' },
  { word: 'public', clue: 'Access modifier allowing unrestricted access to a class member' },
  { word: 'fields', clue: 'Plural of field, referring to an object\'s instance variables' },
  { word: 'client', clue: 'Code that uses another class or object' },
  { word: 'double', clue: 'Primitive data type; also a wrapper class (Double)' },
  { word: 'params', clue: 'Short for parameters, variables in a method signature' },
  { word: 'printf', clue: 'Method for formatted output (e.g., System.out.printf)' },
  { word: 'hidden', clue: 'Refers to instance variables hidden by local variables or parameters of the same name' },
  { word: 'scanner', clue: 'Class (java.util.Scanner) for reading user input' },
  { word: 'indexof', clue: 'String method (indexOf) to find the first occurrence of a substring' },
  { word: 'mutator', clue: 'A method (setter) designed to modify an object\'s instance variable(s)' },
  { word: 'private', clue: 'Access modifier restricting access to members within the same class' },
  { word: 'default', clue: 'Access level if no modifier is specified (package-private)' },
  { word: 'package', clue: 'A namespace that organizes a set of related classes and interfaces' },
  { word: 'javadoc', clue: 'Tool that generates API documentation from comments in source code' },
  { word: 'integer', clue: 'Wrapper class (Integer) for the int primitive type' },
  { word: 'boolean', clue: 'Primitive data type; also a wrapper class (Boolean)' },
  { word: 'compare', clue: 'Often part of method names like compareTo, for ordering objects' },
  { word: 'wrapper', clue: 'A class that encapsulates a primitive data type (e.g., Integer for int)' },
  { word: 'address', clue: 'Memory location where an object is stored, held by a reference variable' },
  { word: 'casting', clue: 'Converting an object reference from one type to another compatible type' },
  { word: 'compile', clue: 'The process of translating source code into bytecode' },
  { word: 'extends', clue: 'Keyword used in class declarations to specify the superclass (for inheritance)' },
  { word: 'tostring', clue: 'Method (toString) that returns a String representation of an object' },
  { word: 'overload', clue: 'Method overloading: defining multiple methods with the same name but different parameter lists' },
  { word: 'argument', clue: 'A value passed to a method when it is invoked' },
  { word: 'instance', clue: 'A concrete occurrence of any object, existing usually during the runtime of a computer program' },
  { word: 'accessor', clue: 'A method (getter) designed to retrieve the value of an object\'s instance variable' },
  { word: 'behavior', clue: 'The set of actions an object can perform, defined by its methods' },
  { word: 'identity', clue: 'Distinguishes one object from another; reference equality (==) checks this' },
  { word: 'implicit', clue: 'Not explicitly stated, e.g., implicit `this` reference' },
  { word: 'explicit', clue: 'Clearly stated, e.g., explicit parameter passing' },
  { word: 'variable', clue: 'A named storage location; instance variables define an object\'s state' },
  { word: 'noargs', clue: 'Refers to a constructor that takes no arguments' },
  { word: 'abstract', clue: 'Keyword for classes that cannot be instantiated or methods that must be implemented by subclasses' },
  { word: 'subclass', clue: 'A class that inherits from another class' },
  { word: 'reference', clue: 'A variable that stores the memory address of an object' },
  { word: 'immutable', clue: 'An object whose state cannot be changed after creation (e.g., String)' },
  { word: 'substring', clue: 'String method to get a part of the string' },
  { word: 'parameter', clue: 'A variable in a method definition that receives a value when the method is called' },
  { word: 'classcast', clue: 'Short for ClassCastException, an error when improperly casting objects' },
  { word: 'interface', clue: 'A reference type that defines a contract of methods a class can implement' },
  { word: 'aliasing', clue: 'When two or more reference variables point to the same object' },
  { word: 'signature', clue: 'A method\'s name along with the types and order of its parameters' },
  { word: 'autoboxing', clue: 'Automatic conversion between a primitive type and its corresponding wrapper class object' },
  { word: 'primitive', clue: 'Basic data types like int, double, boolean, not objects' },
  { word: 'blueprint', clue: 'A class serves as a blueprint for objects' },
  { word: 'formal', clue: 'Formal parameters are the parameters as they appear in the method definition' },
  { word: 'instanceof', clue: 'Operator to check if an object is an instance of a particular class or interface' },
  { word: 'overriding', clue: 'Method overriding: providing a specific implementation for a method inherited from a superclass' },
  { word: 'initialize', clue: 'To assign an initial value to a variable or an object\'s fields, often in a constructor' },
  { word: 'parameters', clue: 'Plural of parameter; the variables listed in a method\'s signature' },
  { word: 'visibility', clue: 'The accessibility of class members (e.g., public, private)' },
  { word: 'mutability', clue: 'The ability of an object\'s state to be changed after creation' },
  { word: 'unboxing', clue: 'Automatic conversion from a wrapper class object to its corresponding primitive type' },
  { word: 'clientcode', clue: 'Code written by a user of a class (the client)' },
  { word: 'deprecated', clue: 'A class or method marked as outdated and may be removed in future versions' },
  { word: 'exceptions', clue: 'Events that occur during program execution that disrupt the normal flow of instructions' },
  { word: 'superclass', clue: 'The parent class from which another class inherits' },
  { word: 'actualargs', clue: 'Actual arguments (or just arguments) are the values passed into a method call' },
];
