/**
 * Unit 8 — 2D Array
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_8: WordCluePair[] = [
  { word: 'at', clue: 'Used conceptually to refer to an element\'s position in a 2D array (at row, col).' },
  { word: 'of', clue: 'Used in phrases like \'array ___ arrays\'.' },
  { word: 'is', clue: 'Used in boolean checks related to 2D array state or elements.' },
  { word: 'it', clue: 'Refers to an element or the 2D array itself in descriptions.' },
  { word: 'in', clue: 'Used in phrases like \'element ___ the grid\'.' },
  { word: 'go', clue: 'Informal term for traversing or processing a 2D array.' },
  { word: 'rc', clue: 'Short for row and column.' },
  { word: 'int', clue: 'Primitive data type commonly stored in 2D arrays.' },
  { word: 'new', clue: 'Keyword used to create a new 2D array object.' },
  { word: 'get', clue: 'Conceptual term for accessing an element at a specific row and column (using [][]).' },
  { word: 'set', clue: 'Conceptual term for modifying an element at a specific row and column (using [][]).' },
  { word: 'row', clue: 'The horizontal dimension of a 2D array.' },
  { word: 'col', clue: 'The vertical dimension of a 2D array.' },
  { word: 'sum', clue: 'Variable used in an accumulator pattern when processing 2D array elements.' },
  { word: 'dim', clue: 'Short for dimension, referring to the number of indices needed (two for 2D).' },
  { word: 'size', clue: 'A property of a 1D array (\'.length\'), used to get the number of columns in a row of a 2D array.' },
  { word: 'null', clue: 'Value that a 2D array variable or elements storing objects can hold if they don\'t point to an object.' },
  { word: 'code', clue: 'The program instructions, including those using 2D arrays.' },
  { word: 'name', clue: 'Identifier for a 2D array variable.' },
  { word: 'type', clue: 'Specifies the kind of elements a 2D array can hold (e.g., int, String).' },
  { word: 'loop', clue: 'Control structure commonly used to iterate through 2D array elements (often nested).' },
  { word: 'each', clue: 'Used in the context of processing \'each\' element in a grid (enhanced for loop).' },
  { word: 'data', clue: 'The elements stored within a 2D array.' },
  { word: 'dims', clue: 'Short for dimensions, referring to the two dimensions of a 2D array.' },
  { word: 'zero', clue: 'The starting index for both rows and columns.' },
  { word: 'grid', clue: 'A common metaphor for a 2D array.' },
  { word: 'cell', clue: 'An individual element at a specific row and column in a 2D array.' },
  { word: 'index', clue: 'A numerical position used to access an element, either row or column.' },
  { word: 'array', clue: 'A fixed-size, sequential collection; a 2D array is an array of these.' },
  { word: 'value', clue: 'The data stored in an element of a 2D array.' },
  { word: 'param', clue: 'Short for parameter, a 2D array can be passed as a parameter.' },
  { word: 'print', clue: 'Method to display the contents of a 2D array or its elements.' },
  { word: 'check', clue: 'To verify a condition related to 2D array elements, rows, or columns.' },
  { word: 'bound', clue: 'Refers to the valid range of indices for rows or columns (0 to length - 1).' },
  { word: 'valid', clue: 'Describes a row or column index that is within the acceptable range for a 2D array.' },
  { word: 'fixed', clue: 'Describes the size of a 2D array\'s rows and columns after it is created.' },
  { word: 'store', clue: 'To place a value into a 2D array element at a specific row and column.' },
  { word: 'fetch', clue: 'To retrieve a value from a 2D array element at a specific row and column.' },
  { word: 'table', clue: 'Conceptual representation of a 2D array with rows and columns.' },
  { word: 'major', clue: 'Used in terms like row-major or column-major order.' },
  { word: 'length', clue: 'A public final field; `array.length` gives rows, `array[r].length` gives columns.' },
  { word: 'object', clue: '2D arrays can store references to these, not just primitive values.' },
  { word: 'public', clue: 'Access modifier, 2D array variables are often declared public or private.' },
  { word: 'method', clue: 'A procedure that might take a 2D array as a parameter or return a 2D array.' },
  { word: 'return', clue: 'Keyword used by methods that return a 2D array or an element from one.' },
  { word: 'define', clue: 'To declare a 2D array variable.' },
  { word: 'create', clue: 'To instantiate a 2D array using \'new\'.' },
  { word: 'access', clue: 'To retrieve or modify an element using its row and column indices (using [][]).' },
  { word: 'string', clue: 'A common type of object stored in 2D arrays.' },
  { word: 'double', clue: 'Primitive type, can be stored directly in a 2D double array.' },
  { word: 'invoke', clue: 'Another term for calling a method that uses 2D arrays.' },
  { word: 'syntax', clue: 'The rules for writing code using 2D arrays (e.g., int[][] arr = ...).' },
  { word: 'modify', clue: 'To change an element\'s value using the assignment operator with row and column indices.' },
  { word: 'assign', clue: 'To store a value in a 2D array element using the assignment operator.' },
  { word: 'bounds', clue: 'The limits of valid indices for rows and columns in a 2D array.' },
  { word: 'column', clue: 'The vertical arrangement of elements in a 2D array.' },
  { word: 'rowcol', clue: 'Refers to accessing an element by specifying its row and then its column.' },
  { word: 'private', clue: 'Access modifier often used for 2D array instance variables within a class.' },
  { word: 'boolean', clue: 'Primitive type, can be stored directly in a 2D boolean array.' },
  { word: 'integer', clue: 'Wrapper class for int, but 2D arrays can store int primitives directly.' },
  { word: 'declare', clue: 'To specify the type and name of a 2D array variable.' },
  { word: 'outside', clue: 'Refers to code external to where a 2D array is declared or used.' },
  { word: 'initial', clue: 'The default value of elements when a 2D array is created (e.g., 0 for int, null for objects).' },
  { word: 'keyword', clue: 'Reserved words like \'new\', \'int\', \'public\', \'private\'.' },
  { word: 'compile', clue: 'To translate code using 2D arrays into bytecode.' },
  { word: 'execute', clue: 'To run a program that uses 2D arrays.' },
  { word: 'program', clue: 'A set of instructions, potentially using 2D arrays.' },
  { word: 'display', clue: 'To show the contents of a 2D array.' },
  { word: 'element', clue: 'An individual item stored at a specific row and column in a 2D array.' },
  { word: 'compare', clue: 'To check if two 2D arrays or elements are equal or have a relationship.' },
  { word: 'literal', clue: 'A fixed value or sequence used to initialize a 2D array (e.g., {{1, 2}, {3, 4}}).' },
  { word: 'indices', clue: 'The plural of index, used to specify both row and column.' },
  { word: 'javadoc', clue: 'Documentation for Java code, including methods that use 2D arrays.' },
  { word: 'outofbnd', clue: 'Short for Index Out Of Bounds, a common 2D array error.' },
  { word: 'allocate', clue: 'To reserve memory for a 2D array object using \'new\'.' },
  { word: 'identity', clue: 'Refers to which specific 2D array object a reference points to.' },
  { word: 'retrieve', clue: 'To get an element from a 2D array using its indices.' },
  { word: 'traverse', clue: 'To visit each element in a 2D array, typically using nested loops.' },
  { word: 'subscript', clue: 'Another term for the index used to access array elements; 2D uses two.' },
  { word: 'onedim', clue: 'Short for one-dimensional array; a 2D array is an array of these.' },
  { word: 'twodim', clue: 'Short for two-dimensional array.' },
  { word: 'rowmajor', clue: 'Order of processing elements in a 2D array by iterating through rows first.' },
  { word: 'colmajor', clue: 'Order of processing elements in a 2D array by iterating through columns first.' },
  { word: 'nestedlp', clue: 'Short for nested loop, used for 2D array traversal.' },
  { word: 'exception', clue: 'An event that disrupts normal program flow, like ArrayIndexOutOfBoundsException.' },
  { word: 'outofbnds', clue: 'Short for Index Out Of Bounds, a common 2D array error.' },
  { word: 'reference', clue: 'A variable that stores the memory address of a 2D array object.' },
  { word: 'execution', clue: 'The process of running code that uses 2D arrays.' },
  { word: 'operation', clue: 'An action performed on a 2D array, like accessing or modifying elements.' },
  { word: 'instantiate', clue: 'To create a 2D array object using \'new\'.' },
  { word: 'structure', clue: 'The organization of data within a 2D array (rows and columns).' },
  { word: 'processor', clue: 'Code (like nested loops) that performs operations on 2D array elements.' },
  { word: 'primitive', clue: 'Data types like int, boolean, double that can be stored directly in 2D arrays.' },
  { word: 'rowindex', clue: 'The first index used to access an element in a 2D array.' },
  { word: 'colindex', clue: 'The second index used to access an element in a 2D array.' },
  { word: 'definition', clue: 'The code that specifies the structure and behavior of your classes using 2D arrays.' },
  { word: 'accessible', clue: 'Describes 2D arrays or their elements that can be used based on scope and modifiers.' },
  { word: 'tostring', clue: 'Method often used to provide a string representation of a 2D array\'s contents (requires helper methods).' },
  { word: 'processing', clue: 'Performing operations on elements within a 2D array, typically using nested loops.' },
  { word: 'dimensions', clue: 'Refers to the number of indices needed to access an element (two for 2D).' },
  { word: 'twodarray', clue: 'A common term for a two-dimensional array.' },
  { word: 'arrayofarr', clue: 'Describes a 2D array as an array of arrays.' },
  { word: 'arrayindex', clue: 'The position used to access an element in an array; 2D uses two.' },
  { word: 'outofbounds', clue: 'Describes an index that is not valid for a 2D array, causing an error.' },
];
