/**
 * Unit 4 — Iteration (Loops)
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_4: WordCluePair[] = [
  { word: 'do', clue: 'Keyword used to begin a do-while loop, guaranteeing at least one execution.' },
  { word: 'or', clue: 'Logical operator (||) used to combine boolean expressions; true if at least one is true.' },
  { word: 'eq', clue: 'Relational operator (==) used to check if two values are equal.' },
  { word: 'ne', clue: 'Relational operator (!=) used to check if two values are not equal.' },
  { word: 'gt', clue: 'Relational operator (>) used to check if the left operand is greater than the right.' },
  { word: 'lt', clue: 'Relational operator (<) used to check if the left operand is less than the right.' },
  { word: 'ge', clue: 'Relational operator (>=) used to check if the left operand is greater than or equal to the right.' },
  { word: 'le', clue: 'Relational operator (<=) used to check if the left operand is less than or equal to the right.' },
  { word: 'go', clue: 'Informal term for starting or continuing a process, like loop execution.' },
  { word: 'for', clue: 'Loop structure commonly used when the number of repetitions is known.' },
  { word: 'int', clue: 'Primitive data type frequently used for loop counter variables.' },
  { word: 'sum', clue: 'Variable used in an accumulator pattern to aggregate values.' },
  { word: 'end', clue: 'The point at which a loop\'s execution is completed.' },
  { word: 'and', clue: 'Logical operator (&&) used to combine boolean expressions; true only if both are true.' },
  { word: 'not', clue: 'Logical operator (!) used to invert a boolean value.' },
  { word: 'run', clue: 'To execute the code within a loop\'s body.' },
  { word: 'key', clue: 'A significant word or value, like a keyword or sentinel value.' },
  { word: 'loop', clue: 'A control structure for repeating a block of code.' },
  { word: 'body', clue: 'The block of statements executed within a loop.' },
  { word: 'flag', clue: 'A boolean variable used to signal a condition or state, often controlling loop flow.' },
  { word: 'exit', clue: 'To terminate the execution of a loop prematurely.' },
  { word: 'step', clue: 'The amount by which a loop control variable is modified in each iteration.' },
  { word: 'test', clue: 'The boolean expression evaluated to decide if a loop continues or stops.' },
  { word: 'true', clue: 'Boolean value that typically allows a while or do-while loop to proceed.' },
  { word: 'stop', clue: 'The action of causing a loop to cease repeating.' },
  { word: 'flow', clue: 'The order in which statements are executed (control flow).' },
  { word: 'pass', clue: 'One complete cycle through a loop\'s body.' },
  { word: 'byte', clue: 'Smallest integer primitive type; less common for loop counters.' },
  { word: 'char', clue: 'Primitive type for single characters; can be iterated over in sequences.' },
  { word: 'void', clue: 'Keyword indicating a method does not return a value, relevant to methods with loops.' },
  { word: 'long', clue: 'Larger integer type for potentially large loop counts.' },
  { word: 'null', clue: 'Value indicating a reference variable points to no object; can be relevant in loop conditions checking for object existence.' },
  { word: 'code', clue: 'The set of instructions that make up a program, including loops.' },
  { word: 'data', clue: 'Information processed by a program, often within loops.' },
  { word: 'next', clue: 'Refers to proceeding to the subsequent iteration of a loop.' },
  { word: 'while', clue: 'Loop structure that repeats as long as its condition is true, checked before each iteration.' },
  { word: 'break', clue: 'Statement to immediately exit the innermost loop or switch.' },
  { word: 'index', clue: 'Numerical position used to access elements in arrays or strings, common in for loops.' },
  { word: 'scope', clue: 'The region of a program where a variable is accessible.' },
  { word: 'trace', clue: 'Step-by-step simulation of code execution, useful for debugging loops.' },
  { word: 'range', clue: 'The set of values a loop counter can take, defined by its start and end.' },
  { word: 'count', clue: 'To keep track of the number of times a loop or event occurs.' },
  { word: 'value', clue: 'The data stored in a variable at a specific time.' },
  { word: 'final', clue: 'Keyword for variables whose value is constant after initialization.' },
  { word: 'start', clue: 'The initial point or value where a loop begins.' },
  { word: 'false', clue: 'Boolean value that typically causes a while or do-while loop to terminate.' },
  { word: 'cycle', clue: 'One complete repetition of a loop\'s process.' },
  { word: 'check', clue: 'The act of evaluating a loop\'s boolean condition.' },
  { word: 'event', clue: 'A condition change that controls an event-controlled loop.' },
  { word: 'fixed', clue: 'Describes a loop designed for a set number of repetitions.' },
  { word: 'block', clue: 'A group of statements enclosed by {}.' },
  { word: 'logic', clue: 'Errors causing incorrect program behavior, often in loop conditions/updates.' },
  { word: 'error', clue: 'A mistake preventing correct program execution or output.' },
  { word: 'total', clue: 'Variable used in an accumulator pattern.' },
  { word: 'limit', clue: 'A boundary value for a loop counter or condition.' },
  { word: 'entry', clue: 'Describes a loop where the condition is checked before the first iteration.' },
  { word: 'valid', clue: 'Describes a condition that allows loop continuation.' },
  { word: 'state', clue: 'The values of variables at a specific point in execution.' },
  { word: 'print', clue: 'To display output, often done repeatedly inside a loop.' },
  { word: 'input', clue: 'Data received by the program, which can influence loop conditions.' },
  { word: 'until', clue: 'Used in some contexts to describe a loop that runs until a condition is met (though not a Java keyword).' },
  { word: 'nested', clue: 'A loop placed entirely within the body of another loop.' },
  { word: 'update', clue: 'The part of a loop that modifies the control variable, moving towards termination.' },
  { word: 'syntax', clue: 'Rules for structuring code elements, including loops.' },
  { word: 'repeat', clue: 'To perform an action multiple times.' },
  { word: 'ending', clue: 'The condition or point that signals loop completion.' },
  { word: 'parens', clue: 'Parentheses (), used around loop conditions and for loop headers.' },
  { word: 'execute', clue: 'To run the instructions in a loop\'s body.' },
  { word: 'inside', clue: 'Refers to code or variables within a loop\'s body.' },
  { word: 'modify', clue: 'To change a variable\'s value or state.' },
  { word: 'assign', clue: 'To store a value in a variable (=).' },
  { word: 'header', clue: 'The first line of a for loop (initialization, condition, update).' },
  { word: 'output', clue: 'Data produced by the program, often iteratively.' },
  { word: 'return', clue: 'Statement to exit a method; can affect loops within the method.' },
  { word: 'method', clue: 'A reusable block of code, potentially containing loops.' },
  { word: 'length', clue: 'Number of elements in an array/string, used for loop bounds.' },
  { word: 'finish', clue: 'To successfully complete a loop\'s iterations.' },
  { word: 'always', clue: 'Describes a condition that is perpetually true, leading to an infinite loop.' },
  { word: 'escape', clue: 'To break out of a loop prematurely.' },
  { word: 'before', clue: 'Describes a loop (like while) where the condition is checked before the body.' },
  { word: 'counter', clue: 'Variable used to count loop iterations.' },
  { word: 'control', clue: 'Management of execution order (control flow).' },
  { word: 'boolean', clue: 'Data type (true/false) used for loop conditions.' },
  { word: 'looping', clue: 'The process of repeatedly executing code.' },
  { word: 'countup', clue: 'Increasing a loop counter\'s value.' },
  { word: 'loopvar', clue: 'Variable managing loop progress.' },
  { word: 'iterate', clue: 'To perform one cycle of a loop.' },
  { word: 'declare', clue: 'To create a variable (type and name).' },
  { word: 'outside', clue: 'Code/variables before or after a loop structure.' },
  { word: 'running', clue: 'Describes an accumulator variable.' },
  { word: 'sentinel', clue: 'Value marking the end of data, controlling an event-controlled loop.' },
  { word: 'compare', clue: 'To check the relationship between values using relational operators.' },
  { word: 'current', clue: 'The value of a variable at a specific moment.' },
  { word: 'process', clue: 'A sequence of operations, often repeated in a loop.' },
  { word: 'perform', clue: 'To carry out an action or instruction within a loop.' },
  { word: 'initial', clue: 'The starting value or state.' },
  { word: 'continue', clue: 'Statement skipping the rest of the current iteration and going to the next.' },
  { word: 'infinite', clue: 'Describes a loop that never terminates.' },
  { word: 'offbyone', clue: 'Error where a loop runs one extra or one too few times.' },
  { word: 'variable', clue: 'A named memory location storing changeable data.' },
  { word: 'boundary', clue: 'Start or end value defining loop limits.' },
  { word: 'stepwise', clue: 'Execution mode pausing after each statement (debugging).' },
  { word: 'totaling', clue: 'Using an accumulator to sum values from iterations.' },
  { word: 'evaluate', clue: 'To determine the result of an expression, like a condition.' },
  { word: 'progress', clue: 'Movement towards the loop\'s termination condition.' },
  { word: 'constant', clue: 'A variable with a fixed value (\'final\').' },
  { word: 'sequence', clue: 'Statements executed in order, characteristic of a loop body.' },
  { word: 'debugger', clue: 'Tool used for step-by-step execution and tracing.' },
  { word: 'strictly', clue: 'Used with < or > to indicate the boundary is not included.' },
  { word: 'increment', clue: 'To increase a numerical variable, typically by 1 (e.g., i++).' },
  { word: 'decrement', clue: 'To decrease a numerical variable, typically by 1 (e.g., i--).' },
  { word: 'iteration', clue: 'A single complete execution of a loop\'s body.' },
  { word: 'condition', clue: 'Boolean expression controlling loop execution.' },
  { word: 'statement', clue: 'A complete instruction in a program.' },
  { word: 'structure', clue: 'The organization of code elements, like a loop\'s components.' },
  { word: 'countdown', clue: 'Decreasing a loop counter towards a lower limit.' },
  { word: 'whileloop', clue: 'Loop where condition is checked before each iteration.' },
  { word: 'execution', clue: 'The process of running a program\'s instructions.' },
  { word: 'operation', clue: 'An action or computation performed by the program.' },
  { word: 'terminate', clue: 'To cause a loop to stop executing.' },
  { word: 'evaluate', clue: 'To determine the value of an expression.' },
  { word: 'logical', clue: 'Refers to boolean expressions and operators used in conditions.' },
  { word: 'initialize', clue: 'To assign an initial value to a variable.' },
  { word: 'dowhileloop', clue: 'Loop where the body executes at least once before the condition is checked at the end.' },
  { word: 'controlvar', clue: 'The variable managing loop execution.' },
  { word: 'comparison', clue: 'Checking the relationship between values using relational operators.' },
  { word: 'terminates', clue: 'Describes the event when a loop finishes.' },
  { word: 'repeating', clue: 'The characteristic of a loop executing multiple times.' },
  { word: 'controlled', clue: 'Describes how a loop\'s execution is managed (e.g., event-_____).' },
  { word: 'accumulate', clue: 'To gather or total values over loop iterations.' },
  { word: 'expression', clue: 'A combination of values, variables, and operators that evaluates to a single value.' },
  { word: 'loopheader', clue: 'The initial line of a for loop containing control elements.' },
  { word: 'nestedloop', clue: 'A loop placed inside another loop.' },
  { word: 'loopbody', clue: 'The statements executed within a loop.' },
  { word: 'exitcondition', clue: 'The logical expression that ends a loop.' },
  { word: 'loopindex', clue: 'The numeric position used in iteration.' },
  { word: 'variabletrace', clue: 'Tracking variable values during loop execution.' },
  { word: 'fixedcount', clue: 'Type of loop that runs a known number of times.' },
  { word: 'eventdriven', clue: 'Describes loops that continue based on external events or conditions (similar to event-controlled).' },
];
