/**
 * Unit 7 — Array (1D)
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_7: WordCluePair[] = [
  { word: 'at', clue: 'Used conceptually to refer to an element\'s position in an array.' },
  { word: 'of', clue: 'Used in phrases like \'array ___ integers\'.' },
  { word: 'is', clue: 'Used in boolean checks related to array state or elements.' },
  { word: 'it', clue: 'Refers to an element or the array itself in descriptions.' },
  { word: 'in', clue: 'Used in phrases like \'element ___ the array\'.' },
  { word: 'go', clue: 'Informal term for traversing or processing an array.' },
  { word: 'int', clue: 'Primitive data type commonly stored in arrays.' },
  { word: 'new', clue: 'Keyword used to create a new array object.' },
  { word: 'get', clue: 'Conceptual term for accessing an element at an index (using []).' },
  { word: 'set', clue: 'Conceptual term for modifying an element at an index (using []).' },
  { word: 'idx', clue: 'Short for index.' },
  { word: 'sum', clue: 'Variable used in an accumulator pattern when processing array elements.' },
  { word: 'size', clue: 'A property of an array (\'.length\') that indicates the number of elements.' },
  { word: 'null', clue: 'Value that an array variable can hold if it doesn\'t point to an array object.' },
  { word: 'code', clue: 'The program instructions, including those using arrays.' },
  { word: 'name', clue: 'Identifier for an array variable.' },
  { word: 'type', clue: 'Specifies the kind of elements an array can hold (e.g., int, String).' },
  { word: 'loop', clue: 'Control structure commonly used to iterate through array elements.' },
  { word: 'each', clue: 'Used in the context of processing \'each\' element in an array (enhanced for loop).' },
  { word: 'data', clue: 'The elements stored within an array.' },
  { word: 'dims', clue: 'Short for dimensions, referring to 1D or 2D arrays.' },
  { word: 'zero', clue: 'The starting index of an array.' },
  { word: 'last', clue: 'Refers to the element at index length - 1.' },
  { word: 'index', clue: 'A zero-based numerical position used to access an element in an array.' },
  { word: 'array', clue: 'A fixed-size, sequential collection of elements of the same data type.' },
  { word: 'value', clue: 'The data stored in an element of an array.' },
  { word: 'param', clue: 'Short for parameter, an array can be passed as a parameter.' },
  { word: 'print', clue: 'Method to display the contents of an array or its elements.' },
  { word: 'check', clue: 'To verify a condition related to array elements or indices.' },
  { word: 'bound', clue: 'Refers to the valid range of indices (0 to length - 1).' },
  { word: 'valid', clue: 'Describes an index that is within the acceptable range for an array.' },
  { word: 'fixed', clue: 'Describes the size of an array after it is created.' },
  { word: 'store', clue: 'To place a value into an array element at a specific index.' },
  { word: 'fetch', clue: 'To retrieve a value from an array element at a specific index.' },
  { word: 'table', clue: 'Conceptual representation of a 2D array.' },
  { word: 'length', clue: 'A public final field of an array that stores the number of elements.' },
  { word: 'object', clue: 'Arrays can store references to these, not just primitive values.' },
  { word: 'public', clue: 'Access modifier, array variables are often declared public or private.' },
  { word: 'method', clue: 'A procedure that might take an array as a parameter or return an array.' },
  { word: 'return', clue: 'Keyword used by methods that return an array or an element from an array.' },
  { word: 'define', clue: 'To declare an array variable.' },
  { word: 'create', clue: 'To instantiate an array using \'new\'.' },
  { word: 'access', clue: 'To retrieve or modify an element using its index (using []).' },
  { word: 'string', clue: 'A common type of object stored in arrays.' },
  { word: 'double', clue: 'Primitive type, can be stored directly in a double array.' },
  { word: 'invoke', clue: 'Another term for calling a method that uses arrays.' },
  { word: 'syntax', clue: 'The rules for writing code using arrays (e.g., int[] arr = ...).' },
  { word: 'insert', clue: 'Conceptual term for placing an element into an array (requires shifting or creating a new array).' },
  { word: 'modify', clue: 'To change an element\'s value using the assignment operator with an index.' },
  { word: 'assign', clue: 'To store a value in an array element using the assignment operator.' },
  { word: 'bounds', clue: 'The limits of valid indices in an array.' },
  { word: 'private', clue: 'Access modifier often used for array instance variables within a class.' },
  { word: 'boolean', clue: 'Primitive type, can be stored directly in a boolean array.' },
  { word: 'integer', clue: 'Wrapper class for int, but arrays can store int primitives directly.' },
  { word: 'declare', clue: 'To specify the type and name of an array variable.' },
  { word: 'outside', clue: 'Refers to code external to where an array is declared or used.' },
  { word: 'initial', clue: 'The default value of elements when an array is created (e.g., 0 for int, null for objects).' },
  { word: 'keyword', clue: 'Reserved words like \'new\', \'int\', \'public\', \'private\'.' },
  { word: 'compile', clue: 'To translate code using arrays into bytecode.' },
  { word: 'execute', clue: 'To run a program that uses arrays.' },
  { word: 'program', clue: 'A set of instructions, potentially using arrays.' },
  { word: 'display', clue: 'To show the contents of an array.' },
  { word: 'element', clue: 'An individual item stored in an array.' },
  { word: 'compare', clue: 'To check if two arrays or elements are equal or have a relationship.' },
  { word: 'literal', clue: 'A fixed value or sequence used to initialize an array (e.g., {1, 2, 3}).' },
  { word: 'javadoc', clue: 'Documentation for Java code, including methods that use arrays.' },
  { word: 'outofbnd', clue: 'Short for Index Out Of Bounds, a common array error.' },
  { word: 'allocate', clue: 'To reserve memory for an array object using \'new\'.' },
  { word: 'identity', clue: 'Refers to which specific array object a reference points to.' },
  { word: 'retrieve', clue: 'To get an element from an array using its index.' },
  { word: 'traverse', clue: 'To visit each element in an array, typically using a loop.' },
  { word: 'subscript', clue: 'Another term for the index used to access array elements.' },
  { word: 'onedim', clue: 'Short for one-dimensional array.' },
  { word: 'twodim', clue: 'Short for two-dimensional array.' },
  { word: 'rowmajor', clue: 'Order of processing elements in a 2D array (by row).' },
  { word: 'colmajor', clue: 'Order of processing elements in a 2D array (by column).' },
  { word: 'exception', clue: 'An event that disrupts normal program flow, like ArrayIndexOutOfBoundsException.' },
  { word: 'outofbnds', clue: 'Short for Index Out Of Bounds, a common array error.' },
  { word: 'reference', clue: 'A variable that stores the memory address of an array object.' },
  { word: 'execution', clue: 'The process of running code that uses arrays.' },
  { word: 'operation', clue: 'An action performed on an array, like accessing or modifying elements.' },
  { word: 'instantiate', clue: 'To create an array object using \'new\'.' },
  { word: 'structure', clue: 'The organization of data within an array.' },
  { word: 'processor', clue: 'Code (like a loop) that performs operations on array elements.' },
  { word: 'primitive', clue: 'Data types like int, boolean, double that can be stored directly in arrays.' },
  { word: 'definition', clue: 'The code that specifies the structure and behavior of your classes using arrays.' },
  { word: 'accessible', clue: 'Describes arrays or their elements that can be used based on scope and modifiers.' },
  { word: 'tostring', clue: 'Method often used to provide a string representation of an array\'s contents (requires helper methods like Arrays.toString()).' },
  { word: 'addelement', clue: 'Conceptual term for adding an element to an array (requires creating a new array).' },
  { word: 'removeelem', clue: 'Conceptual term for removing an element from an array (requires shifting or creating a new array).' },
  { word: 'processing', clue: 'Performing operations on elements within an array, typically using loops.' },
  { word: 'dimensions', clue: 'Refers to the number of indices needed to access an element (e.g., one for 1D, two for 2D).' },
  { word: 'twodarray', clue: 'A common term for a two-dimensional array.' },
  { word: 'onedarray', clue: 'A common term for a one-dimensional array.' },
  { word: 'arraycopy', clue: 'Method in the System class to copy elements from one array to another.' },
  { word: 'arrayindex', clue: 'The position used to access an element in an array.' },
  { word: 'outofbounds', clue: 'Describes an index that is not valid for an array, causing an error.' },
];
