/**
 * Unit 1 — Primitive Types, Variables, and Basic I/O
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_1: WordCluePair[] = [
  { word: 'id', clue: 'Short for identifier, a name given to a variable or method' },
  { word: 'os', clue: 'Abbreviation for Operating System' },
  { word: 'if', clue: 'A conditional statement keyword' },
  { word: 'do', clue: 'Part of a loop construct, do-while' },
  { word: 'pi', clue: 'Mathematical constant, approximately 3.14159' },
  { word: 'int', clue: 'A Java keyword for a whole number type' },
  { word: 'new', clue: 'Keyword used to create an object' },
  { word: 'run', clue: 'To execute a program' },
  { word: 'ide', clue: 'Integrated Development Environment, software for building applications' },
  { word: 'api', clue: 'Application Programming Interface, a set of rules for building software' },
  { word: 'ram', clue: 'Random Access Memory, computer\'s short-term data storage' },
  { word: 'bit', clue: 'Smallest unit of data in a computer' },
  { word: 'bug', clue: 'An error or flaw in a computer program' },
  { word: 'get', clue: 'Common prefix for accessor methods' },
  { word: 'set', clue: 'Common prefix for mutator methods' },
  { word: 'try', clue: 'Keyword for exception handling block' },
  { word: 'for', clue: 'A common loop structure keyword' },
  { word: 'cpu', clue: 'Central Processing Unit, the brain of the computer' },
  { word: 'java', clue: 'The programming language introduced in this course' },
  { word: 'byte', clue: 'Smallest integer primitive type in Java' },
  { word: 'char', clue: 'A single 16-bit Unicode character type' },
  { word: 'true', clue: 'One of the two boolean values' },
  { word: 'void', clue: 'Keyword indicating a method returns no value' },
  { word: 'null', clue: 'A special literal representing no object' },
  { word: 'else', clue: 'Part of an if-else conditional statement' },
  { word: 'long', clue: 'A 64-bit integer data type' },
  { word: 'this', clue: 'Keyword referring to the current instance of a class' },
  { word: 'case', clue: 'Used within a switch statement' },
  { word: 'math', clue: 'A class providing basic numeric operations' },
  { word: 'code', clue: 'Instructions written in a programming language' },
  { word: 'data', clue: 'Information processed or stored by a computer' },
  { word: 'loop', clue: 'A control structure that repeats a block of code' },
  { word: 'cast', clue: 'Explicitly converts data from one type to another' },
  { word: 'args', clue: 'Common name for command-line arguments array in main method' },
  { word: 'file', clue: 'A collection of data stored under a single name' },
  { word: 'float', clue: 'A 32-bit decimal type with less precision than double' },
  { word: 'false', clue: 'Opposite of true in boolean logic' },
  { word: 'class', clue: 'Blueprint for creating Java objects' },
  { word: 'main', clue: 'The entry point method for a Java program' },
  { word: 'print', clue: 'Outputs text without a newline' },
  { word: 'debug', clue: 'Process of finding and fixing errors' },
  { word: 'error', clue: 'A problem that prevents code from running' },
  { word: 'input', clue: 'Data provided to the program by the user' },
  { word: 'scope', clue: 'Region of code where a variable is accessible' },
  { word: 'while', clue: 'A loop structure that repeats as long as a condition is true' },
  { word: 'break', clue: 'Keyword to exit a loop or switch statement' },
  { word: 'final', clue: 'Keyword used to declare a constant or prevent inheritance/overriding' },
  { word: 'index', clue: 'Position of an element in an array or string' },
  { word: 'value', clue: 'The piece of data stored in a variable' },
  { word: 'array', clue: 'A data structure that stores a fixed-size sequential collection of elements of the same type' },
  { word: 'logic', clue: 'The principles of reasoning, often used in conditional statements' },
  { word: 'throw', clue: 'Keyword used to signal an exception' },
  { word: 'double', clue: 'A primitive type that stores decimal numbers' },
  { word: 'method', clue: 'A block of code that performs a task' },
  { word: 'system', clue: 'A class used to access system resources in Java' },
  { word: 'return', clue: 'Keyword to send a value back from a method' },
  { word: 'static', clue: 'Keyword indicating a member belongs to the class, not instances' },
  { word: 'public', clue: 'Access modifier allowing access from any class' },
  { word: 'import', clue: 'Keyword to bring external classes or packages into use' },
  { word: 'object', clue: 'An instance of a class' },
  { word: 'string', clue: 'A sequence of characters, a common class in Java' },
  { word: 'output', clue: 'Information displayed to the user' },
  { word: 'binary', clue: 'Number system with base 2, used by computers' },
  { word: 'editor', clue: 'Software used to write and modify code' },
  { word: 'prompt', clue: 'A message displayed to the user requesting input' },
  { word: 'equals', clue: 'Method to compare the content of two objects' },
  { word: 'switch', clue: 'A control flow statement that selects one of many code blocks to be executed' },
  { word: 'boolean', clue: 'A type that holds true or false values' },
  { word: 'println', clue: 'Outputs text with a newline' },
  { word: 'compile', clue: 'Convert code into bytecode before execution' },
  { word: 'keyword', clue: 'Reserved word with a special meaning in Java' },
  { word: 'braces', clue: 'Used to define a block of code { }' },
  { word: 'literal', clue: 'A fixed value written directly in code' },
  { word: 'scanner', clue: 'Class used to get input from the user' },
  { word: 'console', clue: 'Text-based interface for I/O operations' },
  { word: 'integer', clue: 'A whole number, often represented by the \'int\' type' },
  { word: 'package', clue: 'A namespace that organizes a set of related classes and interfaces' },
  { word: 'private', clue: 'Access modifier restricting access to the same class' },
  { word: 'execute', clue: 'To run or carry out the instructions of a program' },
  { word: 'comment', clue: 'Non-executed text used to describe code (singular form)' },
  { word: 'declare', clue: 'Create a variable without assigning a value' },
  { word: 'convert', clue: 'To change data from one type or format to another' },
  { word: 'variable', clue: 'A container for storing data values' },
  { word: 'bytecode', clue: 'Intermediate code executed by JVM' },
  { word: 'semicolon', clue: 'Ends a Java statement ;' },
  { word: 'comments', clue: 'Non-executed text used to describe code (plural form)' },
  { word: 'overflow', clue: 'Occurs when a value exceeds storage limits' },
  { word: 'constant', clue: 'A variable declared with \'final\' and unchangeable' },
  { word: 'operator', clue: 'Symbol that performs operations on variables and values' },
  { word: 'instance', clue: 'An object created from a class' },
  { word: 'compiler', clue: 'A program that translates source code into machine code or bytecode' },
  { word: 'argument', clue: 'A value passed to a method when it is called' },
  { word: 'abstract', clue: 'Keyword for classes that cannot be instantiated, and for methods without implementation' },
  { word: 'modifier', clue: 'Keywords like public, private, static that define properties of classes, methods, or variables' },
  { word: 'concaten', clue: 'To join strings together' },
  { word: 'variable', clue: 'A named storage location in memory' },
  { word: 'datatype', clue: 'Another term for a variable\'s type' },
  { word: 'primitive', clue: 'Basic data types predefined by Java (e.g., int, double, boolean)' },
  { word: 'statement', clue: 'A complete instruction in Java' },
  { word: 'parameter', clue: 'A variable in a method definition' },
  { word: 'algorithm', clue: 'A step-by-step procedure for solving a problem' },
  { word: 'exception', clue: 'An event that disrupts the normal flow of program execution' },
  { word: 'subclass', clue: 'A class that inherits from another class (superclass)' },
  { word: 'increment', clue: 'To increase the value of a variable, usually by one' },
  { word: 'decrement', clue: 'To decrease the value of a variable, usually by one' },
  { word: 'recursion', clue: 'A technique where a method calls itself' },
  { word: 'remainder', clue: 'The value left over after division, obtained with the modulus operator' },
  { word: 'identifier', clue: 'Name used for variables, classes, and methods' },
  { word: 'initialize', clue: 'Assigning a value to a variable for the first time' },
  { word: 'assignment', clue: 'The operation of storing a value in a variable using \'=\'' },
  { word: 'expression', clue: 'Code that produces a value' },
  { word: 'arithmetic', clue: 'Type of operator used for math operations (+, -, *, /)' },
  { word: 'precedence', clue: 'Determines order of operator evaluation' },
  { word: 'superclass', clue: 'A class from which other classes inherit (parent class)' },
  { word: 'encapsulate', clue: 'Bundling data and methods that operate on the data within a single unit (class)' },
  { word: 'whitespace', clue: 'Characters like space, tab, or newline, used for formatting' },
  { word: 'constructor', clue: 'A special method used to initialize objects' },
];
