/**
 * Unit 6 — Array / ArrayList
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_6: WordCluePair[] = [
  { word: 'at', clue: 'Used in method names like get___ or set___ to specify an index.' },
  { word: 'of', clue: 'Used in phrases like \'list ___ integers\'.' },
  { word: 'is', clue: 'Used in methods like isEmpty() to check a boolean condition.' },
  { word: 'it', clue: 'Refers to an element or the list itself in descriptions.' },
  { word: 'in', clue: 'Used in phrases like \'element ___ the list\'.' },
  { word: 'add', clue: 'Method to insert an element into an ArrayList.' },
  { word: 'get', clue: 'Method to retrieve an element from an ArrayList at a specific index.' },
  { word: 'set', clue: 'Method to replace an element at a specific index in an ArrayList.' },
  { word: 'rem', clue: 'Short for remove, a method to delete elements.' },
  { word: 'idx', clue: 'Short for index.' },
  { word: 'new', clue: 'Keyword used to create a new ArrayList object.' },
  { word: 'size', clue: 'Method that returns the number of elements in an ArrayList.' },
  { word: 'list', clue: 'A common name for an ArrayList variable.' },
  { word: 'null', clue: 'Value that an object reference can hold if it doesn\'t point to an object.' },
  { word: 'code', clue: 'The program instructions, including those using ArrayLists.' },
  { word: 'name', clue: 'Identifier for an ArrayList variable or method.' },
  { word: 'type', clue: 'Specifies the kind of elements an ArrayList can hold (e.g., Integer, String).' },
  { word: 'true', clue: 'Boolean value returned by some ArrayList methods (e.g., add, remove).' },
  { word: 'void', clue: 'Return type of some ArrayList methods (e.g., add(int, E), clear()).' },
  { word: 'from', clue: 'Used in phrases like \'remove ___ the list\'.' },
  { word: 'loop', clue: 'Control structure often used to iterate through ArrayList elements.' },
  { word: 'each', clue: 'Used in the context of processing \'each\' element in a list (enhanced for loop).' },
  { word: 'data', clue: 'The elements stored within an ArrayList.' },
  { word: 'index', clue: 'A zero-based numerical position of an element in an ArrayList.' },
  { word: 'clear', clue: 'Method to remove all elements from an ArrayList.' },
  { word: 'empty', clue: 'Describes an ArrayList that contains no elements.' },
  { word: 'value', clue: 'The data stored in an element of an ArrayList.' },
  { word: 'param', clue: 'Short for parameter, used in method calls.' },
  { word: 'array', clue: 'A fixed-size data structure, contrasted with ArrayList.' },
  { word: 'print', clue: 'Method to display the contents of an ArrayList or its elements.' },
  { word: 'addall', clue: 'Method to add all elements from another collection to an ArrayList.' },
  { word: 'check', clue: 'To verify a condition, like if a list is empty or contains an element.' },
  { word: 'bound', clue: 'Refers to the valid range of indices (0 to size() - 1).' },
  { word: 'valid', clue: 'Describes an index that is within the acceptable range for an ArrayList.' },
  { word: 'remove', clue: 'Method to delete an element from an ArrayList by index or by value.' },
  { word: 'object', clue: 'ArrayLists store references to these, not primitive values directly.' },
  { word: 'public', clue: 'Access modifier for ArrayList methods allowing external use.' },
  { word: 'method', clue: 'A procedure that performs an action on an ArrayList.' },
  { word: 'return', clue: 'Keyword used by methods to send back a value (e.g., get, remove).' },
  { word: 'define', clue: 'To declare an ArrayList variable.' },
  { word: 'create', clue: 'To instantiate an ArrayList using \'new\'.' },
  { word: 'access', clue: 'To retrieve or modify an element using its index.' },
  { word: 'string', clue: 'A common type of object stored in ArrayLists.' },
  { word: 'double', clue: 'Primitive type, but ArrayLists store its wrapper class, Double.' },
  { word: 'import', clue: 'Statement needed to use the ArrayList class.' },
  { word: 'invoke', clue: 'Another term for calling an ArrayList method.' },
  { word: 'syntax', clue: 'The rules for writing code using ArrayLists.' },
  { word: 'insert', clue: 'To add an element at a specific position in the list.' },
  { word: 'modify', clue: 'To change an element\'s value using the set method.' },
  { word: 'length', clue: 'A property of arrays, contrasted with ArrayList\'s size() method.' },
  { word: 'private', clue: 'Access modifier often used for ArrayList instance variables within a class.' },
  { word: 'boolean', clue: 'Return type of methods like add, remove (by object), and isEmpty.' },
  { word: 'integer', clue: 'Wrapper class for the int primitive type, commonly stored in ArrayLists.' },
  { word: 'declare', clue: 'To specify the type and name of an ArrayList variable.' },
  { word: 'outside', clue: 'Refers to code external to where an ArrayList is declared or used.' },
  { word: 'initial', clue: 'The state of an ArrayList when it is first created (empty).' },
  { word: 'keyword', clue: 'Reserved words like \'new\', \'import\', \'public\', \'private\'.' },
  { word: 'compile', clue: 'To translate code using ArrayLists into bytecode.' },
  { word: 'execute', clue: 'To run a program that uses ArrayLists.' },
  { word: 'program', clue: 'A set of instructions, potentially using ArrayLists.' },
  { word: 'display', clue: 'To show the contents of an ArrayList.' },
  { word: 'wrapper', clue: 'Classes like Integer, Double, Boolean used to store primitive values in ArrayLists.' },
  { word: 'element', clue: 'An individual item stored in an ArrayList.' },
  { word: 'compare', clue: 'To check if two ArrayLists or elements are equal or have a relationship.' },
  { word: 'javadoc', clue: 'Documentation for Java code, including ArrayList methods.' },
  { word: 'capacity', clue: 'The internal size of the array used by ArrayList, which can grow.' },
  { word: 'addindex', clue: 'Method to add an element at a specific position.' },
  { word: 'removeby', clue: 'Refers to removing an element either by index or by object.' },
  { word: 'allocate', clue: 'To reserve memory for an ArrayList object using \'new\'.' },
  { word: 'identity', clue: 'Refers to which specific ArrayList object a reference points to.' },
  { word: 'contains', clue: 'Method to check if an ArrayList includes a specific element.' },
  { word: 'isempty', clue: 'Method to check if an ArrayList has no elements.' },
  { word: 'sizezero', clue: 'Describes an empty ArrayList where size() returns 0.' },
  { word: 'retrieve', clue: 'To get an element from an ArrayList using its index.' },
  { word: 'arraylist', clue: 'A resizable array implementation in Java.' },
  { word: 'signature', clue: 'Includes the method name and parameter types, distinguishing methods.' },
  { word: 'reference', clue: 'A variable that stores the memory address of an ArrayList object.' },
  { word: 'execution', clue: 'The process of running code that uses ArrayLists.' },
  { word: 'operation', clue: 'An action performed on an ArrayList, like adding or removing.' },
  { word: 'instantiate', clue: 'To create an ArrayList object using \'new\'.' },
  { word: 'structure', clue: 'The organization of data within an ArrayList.' },
  { word: 'exception', clue: 'An event that disrupts normal program flow, like IndexOutOfBoundsException.' },
  { word: 'outofbound', clue: 'Describes an index that is not valid for an ArrayList.' },
  { word: 'resizable', clue: 'Characteristic of an ArrayList that can change its size.' },
  { word: 'collection', clue: 'ArrayList is part of the Java Collections Framework.' },
  { word: 'definition', clue: 'The code that specifies the structure and behavior of the ArrayList class (or your code using it).' },
  { word: 'accessible', clue: 'Describes ArrayLists or their elements that can be used based on scope and modifiers.' },
  { word: 'tostring', clue: 'Method often overridden to provide a string representation of an ArrayList\'s contents.' },
  { word: 'addelement', clue: 'Method to add a single element to an ArrayList.' },
  { word: 'removeobj', clue: 'Method to remove the first occurrence of a specific object from an ArrayList.' },
  { word: 'indexof', clue: 'Method to find the index of the first occurrence of a specific element.' },
  { word: 'lastindex', clue: 'Method to find the index of the last occurrence of a specific element.' },
  { word: 'sublist', clue: 'Method that returns a view of a portion of the ArrayList.' },
  { word: 'iteration', clue: 'One cycle of processing elements in an ArrayList, often with a loop.' },
  { word: 'processing', clue: 'Performing operations on elements within an ArrayList, typically using loops.' },
];
