/**
 * Unit 5 — Writing Classes
 * Ported from Database.java (original authors: Kabir Khan, Armaan Saini, Atharva Ahir, Rafan Quader)
 */
import type { WordCluePair } from '../logic/types';

export const unit_5: WordCluePair[] = [
  { word: 'new', clue: 'Keyword used to create an instance of a class.' },
  { word: 'is', clue: 'Often used conceptually in \'is-a\' relationships (inheritance, Unit 9).' },
  { word: 'id', clue: 'Short for identifier, used for variable or method names.' },
  { word: 'it', clue: 'Refers to an object instance in descriptions.' },
  { word: 'get', clue: 'Common prefix for accessor methods.' },
  { word: 'set', clue: 'Common prefix for mutator methods.' },
  { word: 'dot', clue: 'Operator (.) used to access members of an object.' },
  { word: 'obj', clue: 'Common abbreviation for object.' },
  { word: 'run', clue: 'To execute a method or program.' },
  { word: 'key', clue: 'Significant word like a keyword or identifier.' },
  { word: 'this', clue: 'Reference to the current object instance within a method or constructor.' },
  { word: 'void', clue: 'Return type indicating a method does not return a value.' },
  { word: 'data', clue: 'Information stored in an object\'s instance variables.' },
  { word: 'null', clue: 'Value indicating an object reference does not point to an object.' },
  { word: 'code', clue: 'The set of instructions defining a class or method.' },
  { word: 'name', clue: 'Identifier given to a class, variable, or method.' },
  { word: 'type', clue: 'Specifies the kind of data a variable can hold or a method can return.' },
  { word: 'call', clue: 'To invoke a method.' },
  { word: 'main', clue: 'The method where program execution typically begins.' },
  { word: 'from', clue: 'Used in phrases like \'created from a class\'.' },
  { word: 'class', clue: 'Defines a blueprint for creating objects.' },
  { word: 'state', clue: 'The current values of an object\'s instance variables.' },
  { word: 'field', clue: 'Another name for an instance variable.' },
  { word: 'final', clue: 'Keyword making a variable\'s value constant after initialization.' },
  { word: 'print', clue: 'Method used to display output, often called on objects.' },
  { word: 'input', clue: 'Data provided to a method or program.' },
  { word: 'scope', clue: 'The region where a variable or method is accessible.' },
  { word: 'value', clue: 'Data stored in a variable.' },
  { word: 'param', clue: 'Short for parameter.' },
  { word: 'javac', clue: 'The Java compiler command.' },
  { word: 'model', clue: 'Often refers to a class representing data or a concept.' },
  { word: 'chain', clue: 'Calling one constructor from another using \'this()\'.' },
  { word: 'object', clue: 'An instance of a class.' },
  { word: 'public', clue: 'Access modifier allowing access from any other class.' },
  { word: 'method', clue: 'A block of code within a class that performs a task.' },
  { word: 'return', clue: 'Keyword used to send a value back from a method.' },
  { word: 'define', clue: 'To create or specify the structure of a class or method.' },
  { word: 'create', clue: 'To instantiate an object using the \'new\' keyword.' },
  { word: 'access', clue: 'To get or modify the value of an instance variable or call a method.' },
  { word: 'static', clue: 'Keyword for members belonging to the class itself, not specific instances.' },
  { word: 'string', clue: 'A class representing sequences of characters, often used with objects.' },
  { word: 'double', clue: 'Primitive data type, can be used for instance variables.' },
  { word: 'import', clue: 'Statement to use classes from other packages.' },
  { word: 'invoke', clue: 'Another term for calling a method.' },
  { word: 'syntax', clue: 'The rules for writing valid code.' },
  { word: 'private', clue: 'Access modifier restricting access to within the class.' },
  { word: 'mutator', clue: 'A method that changes the state (instance variables) of an object.' },
  { word: 'boolean', clue: 'Primitive type, can be an instance variable or parameter type.' },
  { word: 'integer', clue: 'Whole number primitive type (int), often used for instance variables.' },
  { word: 'declare', clue: 'To create a variable or method by specifying its type and name.' },
  { word: 'outside', clue: 'Refers to code in other classes that might interact with an object.' },
  { word: 'initial', clue: 'The starting value assigned during initialization.' },
  { word: 'keyword', clue: 'A reserved word in Java with a specific meaning.' },
  { word: 'compile', clue: 'To translate source code into bytecode.' },
  { word: 'execute', clue: 'To run the compiled code.' },
  { word: 'program', clue: 'A set of instructions, often using classes and objects.' },
  { word: 'display', clue: 'To show output, often using methods.' },
  { word: 'accessor', clue: 'A method that retrieves the value of an instance variable.' },
  { word: 'behavior', clue: 'What an object can do, defined by its methods.' },
  { word: 'instance', clue: 'A specific object created from a class blueprint.' },
  { word: 'javabean', clue: 'A class following specific conventions (private fields, public getters/setters).' },
  { word: 'overload', clue: 'Having multiple methods or constructors with the same name but different parameters.' },
  { word: 'parameter', clue: 'A variable declared in a method or constructor signature that receives a value.' },
  { word: 'attribute', clue: 'Another name for an instance variable or field.' },
  { word: 'allocate', clue: 'To reserve memory space for an object using \'new\'.' },
  { word: 'strictly', clue: 'Used with access modifiers to describe tight restrictions.' },
  { word: 'identity', clue: 'Refers to which specific object an object reference points to.' },
  { word: 'constructor', clue: 'Special method used to initialize a new object when it\'s created.' },
  { word: 'signature', clue: 'Includes the method name and parameter types, used to distinguish overloaded methods.' },
  { word: 'blueprint', clue: 'A metaphor for a class, illustrating its role in creating objects.' },
  { word: 'reference', clue: 'A variable that stores the memory address of an object.' },
  { word: 'shadowing', clue: 'When a local variable or parameter has the same name as an instance variable.' },
  { word: 'execution', clue: 'The process of running a program or method.' },
  { word: 'operation', clue: 'An action performed by a method.' },
  { word: 'instantiate', clue: 'To create an object from a class using the \'new\' keyword.' },
  { word: 'structure', clue: 'The organization of a class (fields, constructors, methods).' },
  { word: 'encapsulate', clue: 'To bundle data (fields) and methods that operate on the data within a single unit (a class).' },
  { word: 'initialize', clue: 'To assign an initial value to a variable, often done in constructors.' },
  { word: 'default', clue: 'Refers to the constructor with no parameters, automatically provided if no other constructors are defined.' },
  { word: 'overloaded', clue: 'Describes methods or constructors with the same name but different parameter lists.' },
  { word: 'abstraction', clue: 'Hiding complex implementation details and showing only essential features.' },
  { word: 'objectref', clue: 'A variable that points to an object in memory.' },
  { word: 'definition', clue: 'The code that specifies the structure and behavior of a class or method.' },
  { word: 'accessible', clue: 'Describes members that can be used from a particular location based on access modifiers.' },
  { word: 'tostring', clue: 'A common method used to provide a string representation of an object.' },
  { word: 'classfield', clue: 'An instance variable defined within a class.' },
  { word: 'cohesion', clue: 'Principle where a class has a single, well-defined purpose.' },
  { word: 'modular', clue: 'Code organized into independent, reusable units like classes.' },
  { word: 'responsibility', clue: 'A task or duty assigned to a class or method.' },
];
